import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body>
  
  {/* added header and footer */}
      <header 
        style={{
          backgroundColor: "#111111",

          color: "white",
          padding: "1rem",
      }}>ec
            <div className="flex space-x-5 align-middle justify-evenly">
            <div>Logo ECOMMORCE</div>
            <div>Ангилал</div>
            <div>Search bar</div>
            <div>icon heart</div> 
            <div>icon cart</div> 
            <div>Бүргүүлэх</div> 
            <div>Нэвтрэх</div>             
            <p>2024 Ecommerce MN</p>
          </div>   
      </header>

        {children}

      <footer
        style={{
          backgroundColor: "#111111",
          top: "798px",
          gap: "43px",
          width: "100%",
          height: "282x",
          padding: "64px 220px",
          color: "white",
        }}>
          <div className="flex space-x-5 align-middle justify-evenly">
            <div>Logo</div>
            <div>icon (976)7007-1234</div>
            <div>icon contact@ecommerce.mn</div>
            <br/> 
        <p>2024 Ecommerce MN</p>
          </div>     
      </footer>
  {/* close header and footer */}
  
      </body>
    </html>
  );
}
